"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const Authmiddleware_1 = __importDefault(require("../middlewares/Authmiddleware"));
const adminController_1 = require("../controller/adminController");
const restaurantController_1 = require("../controller/restaurantController");
const deliveryController_1 = require("../controller/deliveryController");
const router = express_1.default.Router();
router.post('/adminlogin', adminController_1.adminlogin);
router.get('/users', Authmiddleware_1.default, adminController_1.getUsers);
router.put('/users/:id/block', Authmiddleware_1.default, adminController_1.blockUnblockUser);
router.post('/restaurantsignup', Authmiddleware_1.default, restaurantController_1.registerRestaurant);
router.post('/deliverypersonsignup', Authmiddleware_1.default, deliveryController_1.registerDeliveryPerson);
router.get('/restaurants', restaurantController_1.getRestaurants);
router.put('/restaurant/:id/block', Authmiddleware_1.default, restaurantController_1.blockUnblockRestaurant);
router.get('/delivery-persons', deliveryController_1.getDeliveryPersons);
router.put('/delivery-persons/:id/block', Authmiddleware_1.default, deliveryController_1.blockUnblockDeliveryboy);
router.put('/updaterestaurant/:id', Authmiddleware_1.default, restaurantController_1.updateRestaurant);
router.get('/restaurant/:id', Authmiddleware_1.default, restaurantController_1.getRestaurantById);
router.put('/updatefooditem/:id', restaurantController_1.updateFoodItem);
router.get('/fooditem/:id', Authmiddleware_1.default, restaurantController_1.getFoodItemById);
router.get('/total-users', adminController_1.getTotalUsers);
router.get('/total-restaurants', adminController_1.getTotalRestaurants);
router.get('/total-orders', adminController_1.getTotalOrders);
router.get('/total-revenue', adminController_1.getTotalRevenue);
router.get('/top-restaurants', adminController_1.getTopRestaurants);
exports.default = router;
