export const ADD_TO_CART_REQUEST = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART";
export const ADD_TO_CART_FAIL = "ADD_TO_CART";




export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const SAVE_DELIVERY_INFO = "SAVE_DELIVERY_INFO";
export const SET_RESTAURANT_ID = "SET_RESTAURANT_ID";
export const UPDATE_DELIVERY_INFO='UPDATE_DELIVERY_INFO';
export const FETCH_CART_ITEMS='FETCH_CART_ITEMS'