// constants/deliveryBoyConstants.js
export const FETCH_DELIVERYBOYS_LOGIN_REQUEST = 'FETCH_DELIVERYBOYS_REQUEST';
export const FETCH_DELIVERYBOYS_LOGIN_SUCCESS = 'FETCH_DELIVERYBOYS_SUCCESS';
export const FETCH_DELIVERYBOYS_LOGIN_FAIL = 'FETCH_DELIVERYBOYS_FAIL';

export const ADD_DELIVERYBOY_REQUEST = 'ADD_DELIVERYBOY_REQUEST';
export const ADD_DELIVERYBOY_SUCCESS = 'ADD_DELIVERYBOY_SUCCESS';
export const ADD_DELIVERYBOY_FAIL = 'ADD_DELIVERYBOY_FAIL';

export const DELETE_DELIVERYBOY_REQUEST = 'DELETE_DELIVERYBOY_REQUEST';
export const DELETE_DELIVERYBOY_SUCCESS = 'DELETE_DELIVERYBOY_SUCCESS';
export const DELETE_DELIVERYBOY_FAIL = 'DELETE_DELIVERYBOY_FAIL';

export const UPDATE_DELIVERYBOY_REQUEST = 'UPDATE_DELIVERYBOY_REQUEST';
export const UPDATE_DELIVERYBOY_SUCCESS = 'UPDATE_DELIVERYBOY_SUCCESS';
export const UPDATE_DELIVERYBOY_FAIL = 'UPDATE_DELIVERYBOY_FAIL';
