//USER REGISTRATION

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS= "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const OTP_USER_REQUEST ="OTP_USER_REQUEST"
export const  OTP_USER_SUCCESS="OTP_USER_SUCCESS"
export const OTP_USER_FAIL="OTP_USER_FAIL"


export const REGISTER_GOOGLE_REQUEST='REGISTER_GOOGLE_REQUEST'
export const REGISTER_GOOGLE_SUCCESS='REGISTER_GOOGLE_SUCCESS'
export const REGISTER_GOOGLE_FAIL='REGISTER_GOOGLE_FAIL'


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS= "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"